### PR TITLE
Fix notification popup redirect to store not having navigation bar

### LINKED ISSUE #63: [BUG] Navigation Bar Disappearing
Go to shop using the popup appears after finishing a focus session causes the navigation bar to disappear.
Solution reference: https://stackoverflow.com/questions/57560751/flutter-navigation-bar-change-tab-from-another-page

### PR DESCRIPTION
**Pull request by trun-g**
Close #63

### CODE REVIEW

File: source/tubtrunk/lib/Views/mainView.dart [hunk 1]
```diff
@@ -12,20 +13,21 @@ class MainView extends StatefulWidget {
   _MainViewState createState() => _MainViewState();
 }
 
-class _MainViewState extends State<MainView> {
-  int _selectedIndex = 0;
+class _MainViewState extends State<MainView> with SingleTickerProviderStateMixin {
```
Comment (trun-g) [inline source/tubtrunk/lib/Views/mainView.dart:16]: Mixin required to use TabController

File: source/tubtrunk/lib/Views/timerView.dart [hunk 2]
```diff
@@ -15,7 +15,7 @@ class TimerView extends StatefulWidget {
   _TimerViewState createState() => _TimerViewState();
 }
 
-class _TimerViewState extends State<TimerView> with WidgetsBindingObserver {
+class _TimerViewState extends State<TimerView> with WidgetsBindingObserver, AutomaticKeepAliveClientMixin {
```
Comment (trun-g) [inline source/tubtrunk/lib/Views/timerView.dart:18]: This mixin allows the state of TimerView to be saved when changing view

**Review by thain-gd — APPROVED** [review]
Clarifications are clean, this is good to merge!
